### ISSUE TITLE
pycorrfit starting issues when installed as debian package

### ISSUE THREAD

**Issue by mestia** [FCS-analysis/PyCorrFit#172]
Since version 1.0.0 I get this traceback when I try to start pycorrfit installed as the Debian package.
Any hint how to solve it ? thanks!

Traceback (most recent call last):
  File "/usr/bin/pycorrfit", line 11, in <module>
    load_entry_point('pycorrfit==1.0.0', 'gui_scripts', 'pycorrfit')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2301, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'Main'

**Comment by paulmueller** [comment]
Thanks for finding this bug. I fixed it in the latest commit in the development branch (PyCorrFit version 1.0.1.dev3).
https://github.com/FCS-analysis/PyCorrFit/commit/6eb76e09b9418c57d14bd71e62ad7b64272c452b
