### ISSUE TITLE
ImportError: cannot import name 'MutableSet' from 'collections'

### ISSUE THREAD

**Issue by GrantFoley** [FCS-analysis/PyCorrFit#206]
I am attempting to install from PyCorrFit from source, but this error message keeps popping up. How should I got about fixing this issue?

**Comment by paulmueller** [comment]
Do you have the full traceback? Looks like some third-party module does not support the latest Python version. `MutableSet` is in `collections.abc`.

**Comment by GrantFoley** [comment]
Traceback (most recent call last):
  File "C:\Users\Baker Lab 432-A\.conda\envs\PyCorrFit\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Baker Lab 432-A\.conda\envs\PyCorrFit\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\Baker Lab 432-A\.conda\envs\PyCorrFit\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Baker Lab 432-A\PyCorrFit\pycorrfit\__init__.py", line 10, in <module>
    from .correlation import Correlation
  File "C:\Users\Baker Lab 432-A\PyCorrFit\pycorrfit\correlation.py", line 8, in <module>
    from . import fit
  File "C:\Users\Baker Lab 432-A\PyCorrFit\pycorrfit\fit.py", line 5, in <module>
    import lmfit
  File "C:\Users\Baker Lab 432-A\.conda\envs\PyCorrFit\lib\site-packages\lmfit\__init__.py", line 43, in <module>
    from .model import Model, CompositeModel
  File "C:\Users\Baker Lab 432-A\.conda\envs\PyCorrFit\lib\site-packages\lmfit\model.py", line 14, in <module>
    from collections import MutableSet
ImportError: cannot import name 'MutableSet' from 'collections' (C:\Users\Baker Lab 432-A\.conda\envs\PyCorrFit\lib\collections\__init__.py)

**Comment by GrantFoley** [comment]
Here is the most recent traceback when I try to run PyCorrFit using the python -m pycorrfit command

**Comment by paulmueller** [comment]
Which version of `lmfit` do you have? In version 1.1.0, this import is not there anymore: https://github.com/lmfit/lmfit-py/blob/1.1.0/lmfit/model.py

**Comment by GrantFoley** [comment]
I currently have lmfit 0.9.2 installed.

**Comment by paulmueller** [comment]
OK, it's probably that. You have to upgrade lmfit.

**Comment by GrantFoley** [comment]
Ok I think that did it. PyCorrFit was able to open, and I was able to load my .cor file into it. Thanks to both of you for all of your help. I will let you know if any more issues arise.
